# Generated by Django 3.0.7 on 2021-02-08 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201009_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gst_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='GST/HST Number'),
        ),
    ]
