# Generated by Django 3.0.7 on 2021-02-08 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0068_auto_20210208_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipping',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='GST/HST #'),
        ),
    ]
